export const HOMEPAGE_CONTENT_SLOT_ORDER = [
	'Slot1',
	'Slot2',
	'HomePageMainBannerSlot',
	'UpcomingOrderStatus',
	'Slot3A',
	'Slot3B',
	'DealsSlot',
	'DontForgetSlot',
	'StartWhereYouLeftSlot',
	'Slot4',
	'Slot5',
	'Slot6',
	'Slot7',
	'Top5bestSellingSlot',
	'Slot8',
	'SpecialOffersSlot',
	'GiftIdeasSlot',
	'ShoppingJourneySlot',
	'Slot9',
	'Slot10',
	'Slot11',
	'Slot12',
	'Slot13',
	'Slot14',
	'Slot15',
	'AmplienceSlot14',
	'AmplienceSlot15',
	'AmplienceSlot16',
	'AmplienceSlot17',
	'AmplienceSlot18',
	'AmplienceSlot19',
	'AmplienceSlot20',
	'AmplienceSlot21',
	'AmplienceSlot22',
	'AmplienceSlot23',
	'AmplienceSlot24',
	'AmplienceSlot25',
	'AmplienceSlot26',
	'AmplienceSlot27',
	'AmplienceSlot28',
	'AmplienceSlot29',
	'AmplienceSlot30',
	'Service',
	'ExtraRichRelevance'
];
export const FOOTER_CONTENT_SLOTS = [
	'FooterTopFull',
	'FooterTop',
	'FooterMiddleA',
	'FooterMiddleB',
	'FooterMiddleC',
	'Footer',
	'FooterMciCertificate'
];
export const FOOTER_MIDDLE_CONTENT_SLOTS = ['FooterTop', 'FooterMiddleC', 'FooterMiddleB'];
export const slotGroups = {
	Slot3A: 1,
	Slot3B: 1,
	DealsSlot: 1
};
